name: saferoute_app
description: SafeRoute - Navegación Segura para Flotas en Chiapas
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  # Red
  http: ^1.2.2
  web_socket_channel: ^3.0.1

  # Almacenamiento seguro
  flutter_secure_storage: ^9.2.2

  # Mapas
  flutter_map: ^8.0.0
  latlong2: ^0.9.1

  # Ubicación
  geolocator: ^13.0.2

  # Variables de entorno
  flutter_dotenv: ^5.2.1

  # Subimos a la v6 para usar .contains() y corregir tu error
  connectivity_plus: ^6.1.1

  speech_to_text: ^7.4.0
  
  # Agregado para notificaciones
  flutter_local_notifications: ^17.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icono.png"

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
